name: Backend CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore K4-TeamProj.slnx
      
      - name: Build project
        run: dotnet build K4-TeamProj.slnx --configuration Release --no-restore
      
      - name: Run tests
        run: dotnet test K4-TeamProj.slnx --configuration Release --no-build --verbosity normal
